include device/qcom/msm7630_surf/BoardConfig.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := f11d

TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=f11d
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_FORCE_RAMDISK_ADDRESS := 0x1500000
KERNEL_DEFCONFIG := is3jp-perf_defconfig
KERNEL_HEADERS_COMMON := kernel/fujitsu/f11d/include

BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 133562368 # 128MiB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 419430400 # 400MiB
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_FLASH_BLOCK_SIZE := 262144
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

# hack to prevent llvm from building
BOARD_USE_QCOM_LLVM_CLANG_RS := true
USE_OPENGL_RENDERER := true

BOARD_HAVE_BLUETOOTH := true

BOARD_EGL_CFG := device/fujitsu/f11d/egl.cfg

BOARD_WLAN_DEVICE := bcmdhd
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
WIFI_DRIVER_FW_PATH_STA := "sta"
WIFI_DRIVER_FW_PATH_AP  := "ap"
